version: '3.4'

services:

    storm_zookeeper:
        image: zookeeper:${ZOO_VERSION:-3.4.11}
        environment:
            ZOO_PORT: ${ZOO_PORT:-2181}
        networks:
            - bshm_net
        volumes:
            - zoo_data:/data
        restart: always

    nimbus:
        image: storm:${STORM_VERSION:-1.1.1}
        command: storm nimbus
        depends_on:
            - storm_zookeeper
        networks:
            - bshm_net
        ports:
            - "6627:6627"
        volumes:
            - ./logs:/logs
            - ./conf:/conf
            - data:/data
        restart: always

    supervisor:
        build: ./build
        image: storm-bshm:${STORM_VERSION:-1.1.1}
        command: storm supervisor
        depends_on:
            - nimbus
            - storm_zookeeper
        networks:
            - bshm_net
        volumes:
            - ./logs:/logs
            - ./conf:/conf
            - data:/data
        restart: always

    ui:
        image: storm:${STORM_VERSION:-1.1.1}
        command: storm ui
        depends_on:
            - storm_zookeeper
            - nimbus
        networks:
            - bshm_net
        ports:
            - "8080:8080"
        volumes:
            - ./logs:/logs
            - ./conf:/conf
            - data:/data
        restart: always

volumes:
    data:
    zoo_data:

networks:
    bshm_net:
        external: true
